### ISSUE TITLE
Can't access /people on production

### ISSUE THREAD

**Issue by pulkitsharma07** [StartupWichita/startupwichita.com#92]
I guess it is throwing an exception.

http://www.startupwichita.com/people

**Comment by kentonh** [comment]
It looks like this is caused by a tag with a nil value.

A Person has added a tag that the template can't handle.
@pulkitsharma07 is this something you'd like to work on?

**Comment by alienxp03** [comment]
I'd like to work on it if there are no takers yet :)

**Comment by kentonh** [comment]
@alienxp03 It's all you, friendo

**Comment by alienxp03** [comment]
@kentonh Any chance I can see the log errors?

**Comment by kentonh** [comment]
Here's what I pulled when I filed the ticket.

```2017-09-29T20:18:54.608722+00:00 app[web.1]: Started GET "/news/220" for 98.191.133.174 at 2017-09-29 20:18:54 +0000
2017-09-29T20:18:54.610486+00:00 app[web.1]: Processing by NewsController#show as HTML
2017-09-29T20:18:54.610535+00:00 app[web.1]:   Parameters: {"id"=>"220"}
2017-09-29T20:18:54.625640+00:00 app[web.1]:   Rendered topics/_disqus.html.erb (0.1ms)
2017-09-29T20:18:54.628260+00:00 app[web.1]:   Rendered news/show.html.erb within layouts/application (12.5ms)
2017-09-29T20:18:54.630830+00:00 app[web.1]: Completed 200 OK in 20ms (Views: 12.5ms | ActiveRecord: 4.2ms)
2017-09-29T20:19:41.198442+00:00 app[web.1]: Started GET "/people" for 98.191.133.174 at 2017-09-29 20:19:41 +0000
2017-09-29T20:19:41.201160+00:00 app[web.1]: Processing by PeopleController#index as HTML
2017-09-29T20:19:41.371193+00:00 app[web.1]:   Rendered people/index.html.erb within layouts/application (166.8ms)
2017-09-29T20:19:41.372009+00:00 app[web.1]: Completed 500 Internal Server Error in 171ms (ActiveRecord: 72.5ms)
2017-09-29T20:19:41.375694+00:00 app[web.1]:
2017-09-29T20:19:41.375696+00:00 app[web.1]: ActionView::Template::Error (undefined method `id' for nil:NilClass):
2017-09-29T20:19:41.375699+00:00 app[web.1]:     27:             </p>
2017-09-29T20:19:41.375701+00:00 app[web.1]:     28:             <h4>Interests</h4>
2017-09-29T20:19:41.375701+00:00 app[web.1]:     29:             <p>
2017-09-29T20:19:41.375702+00:00 app[web.1]:     30:               <% if Person.all_interest_tags.size > 0 %>
2017-09-29T20:19:41.375703+00:00 app[web.1]:     31:                 <% Person.all_interest_tags.each do |tag| %>
2017-09-29T20:19:41.375704+00:00 app[web.1]:     32:                   <span class="tags"><%= link_to tag['name'], people_with_interests_path(tag: tag['name']) %></span>
2017-09-29T20:19:41.375705+00:00 app[web.1]:     33:                 <% end %>
2017-09-29T20:19:41.375706+00:00 app[web.1]:   app/models/person.rb:66:in `block in all_interest_tags'
2017-09-29T20:19:41.375707+00:00 app[web.1]:   app/models/person.rb:66:in `all_interest_tags'
2017-09-29T20:19:41.375708+00:00 app[web.1]:   app/views/people/index.html.erb:30:in `block in _app_views_people_index_html_erb___3240603264314269510_69913411392160'
2017-09-29T20:19:41.375709+00:00 app[web.1]:   app/views/people/index.html.erb:1:in `_app_views_people_index_html_erb___3240603264314269510_69913411392160'
2017-09-29T20:19:41.375709+00:00 app[web.1]:   app/controllers/people_controller.rb:16:in `index'
2017-09-29T20:19:41.375710+00:00 app[web.1]:
2017-09-29T20:19:41.375711+00:00 app[web.1]:```

**Comment by alienxp03** [comment]
Seems like could be an issue with `acts_as_ordered_taggable_on`. Created PR [102](https://github.com/StartupWichita/startupwichita.com/pull/102) 🙂

**Comment by kentonh** [comment]
@alienxp03 I've deployed this PR to production, but the problem persists.

**Comment by alienxp03** [comment]
Same error I suppose? I'll check on it later tonight (_my timezone_) 😁

**Comment by pulkitsharma07** [comment]
I'll take a look into it tonight, btw, isn't the page taking too long to load ?
It takes about 10-11 seconds for me.

@kentonh, Did this happen after deploying the PR #102 ?

**Comment by kentonh** [comment]
@pulkitsharma07 you're right! and @alienxp03, it's not the same error. It looks like a Heroku timeout, probably based all the gravitar checks on #98.
